name: Release
'on':
  pull_request:
    types: [opened, edited, reopened, synchronize]
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npmrc
        run: >-
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >>
          .npmrc
      - name: Install dependencies
        run: npm install
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
      - name: Run Jest
        run: npm test