name: Release
"on":
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: npmrc
        run: >-
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >>
          .npmrc
      - name: Install dependencies
        run: npm install
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
      - name: Run Jest
        run: npm test
      - name: "Release with semantic release"
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          NPM_TOKEN: "${{ secrets.NPM_TOKEN }}"
